persistence:
  enabled: true
  size: 2Gi
service:
  type: NodePort
  nodePort: 30300
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.openwhisk.svc.cluster.local
      access: proxy
      isDefault: true
